development:
  adapter: mysql2
  encoding: utf8
  database: west_alko_dev
  username: root
  password: admin

test:
  adapter: mysql2
  encoding: utf8
  database: west_alko_test
  username: root
  password: admin

production:
  adapter: mysql2
  encoding: utf8
  database: west_alko_prod
  username: root
  password: admin
