development:
  adapter: mysql2
  encoding: utf8
  database: west_alko_development
  username: job
  password: ''

test:
  adapter: mysql2
  encoding: utf8
  database: west_alko_test
  username: job
  password: ''

production:
  adapter: mysql2
  encoding: utf8
  database: west_alko_production
  username: job
  password: ''
