development:
  adapter: mysql2
  encoding: utf8
  database: westalko
  username: artjom
  password: 'dilainik'

test:
  adapter: mysql2
  encoding: utf8
  database: westalko_test
  username: root
  password: ''

production:
  adapter: mysql2
  encoding: utf8
  database: westalko_prod
  username: root
  password: ''
