development:
  adapter: mysql2
  encoding: utf8
  database: west_alko_dev
  username: root
  password: 'Ghfdlbycr12mysql'

test:
  adapter: mysql2
  encoding: utf8
  database: west_alko_test
  username: root
  password: 'Ghfdlbycr12mysql'

production:
  adapter: mysql2
  encoding: utf8
  database: west_alko_prod
  username: root
  password: ''
