development:
  adapter: mysql2
  encoding: utf8
  database: west_alko_dev
  username: root
  password: ''

test:
  adapter: mysql2
  encoding: utf8
  database: west_alko_test
  username: root
  password: ''

production:
  adapter: mysql2
  encoding: utf8
  database: west_alko_prod
  username: root
  password: ''
